<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>59945660-5f3d-4052-b320-d926789d7f1e</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <StartupObject>AspCoreForReactApi.Program</StartupObject>
  </PropertyGroup>

  <!--<ItemGroup>
    <Content Remove="assets\Editorials\list.json" />
    <Content Remove="assets\imagesList.json" />
  </ItemGroup>-->

  <!--<ItemGroup>
    <None Remove="assets\images\Adon_Exclusive_Model_Don_Hood_By_Blake_Ballard.jpg" />
  </ItemGroup>-->

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.13" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.5" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
  </ItemGroup>

  <ItemGroup>
    <AssetFiles Include="assets\**\*" />
    <AssetFiles Include="Assets\**\*" />
  </ItemGroup>

  <Target Name="CopyAssetsToOutput" AfterTargets="Build">
    <Copy SourceFiles="@(AssetFiles)" DestinationFiles="@(AssetFiles->'$(OutputPath)Assets\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>

  <Target Name="CopyAssetsToPublish" AfterTargets="Publish">
    <Copy SourceFiles="@(AssetFiles)" DestinationFiles="@(AssetFiles->'$(PublishDir)Assets\%(RecursiveDir)%(Filename)%(Extension)')" SkipUnchangedFiles="true" />
  </Target>

  <!--<ItemGroup>
    <None Update="assets\Editorials\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>-->

  <!--<ItemGroup>
    <None Include="assets\Editorials\list.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="assets\imagesList.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>-->

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

  <!--<ItemGroup>
    <TypeScriptCompile Include="assets\images\Adon_Exclusive_Model_Don_Hood_By_Blake_Ballard.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </TypeScriptCompile>
  </ItemGroup>-->
</Project>
